FROM cypress/included:14.0.0

USER root

WORKDIR /home

RUN git clone https://github.com/manuel-agilgob/self-hosted-runner.git \
    && cd self-hosted-runner \
    && npm install

WORKDIR /home/self-hosted-runner

ARG folder_name
ENV folder_name=${folder_name}

COPY run_tests.sh .
RUN chmod +x run_tests.sh
CMD [ "./run_tests.sh" ]

